/**
 * The whole book "Mastering Prompt Engineering" as a list of sections (its own headings and worked examples),
 * each assigned to the Prompt School chapter that teaches it. This is the enforcement of the Director's rule
 * (2026-09-20): the School covers the COMPLETE book and skips no segment. Every lesson declares the sections it
 * covers (`covers`), and the content test fails when an authored chapter leaves any of its sections uncovered,
 * or when a lesson claims a section that is not in this map or belongs to another chapter.
 *
 * A chapter that is not authored yet keeps its sections here as the to-do list; `provisional` marks entries whose
 * granularity will be refined (split or renamed) when the chapter is written from the source text. Front matter
 * (copyright, ISBN, acknowledgements) and the table of contents are not teaching content and are not listed.
 *
 * Source: C:\DAVOR_PRIVATE\AI\My_Books\Manual - Prompt Engineering ADVANCED\Mastering_Prompt_Engineering.md
 */

export interface BookSection {
  /** Stable id, referenced by lessons. */
  id: string;
  /** Slug of the School chapter that teaches it (see outline.ts). */
  chapter: string;
  /** The book's own wording for the heading or example. */
  title: string;
  provisional?: boolean;
}

function group(chapter: string, prefix: string, items: Array<[string, string]>, provisional = false): BookSection[] {
  return items.map(([id, title]) => ({ id: `${prefix}-${id}`, chapter, title, ...(provisional ? { provisional: true } : {}) }));
}

/** The four parts every Appendix B blueprint has in the book, as map entries. */
function blueprint(n: number, title: string): Array<[string, string]> {
  const id = `bp${String(n).padStart(2, "0")}`;
  const name = `Blueprint ${n}: ${title}`;
  return [
    [`${id}-explained`, `${name}, the scenario, goal and detailed explanation (techniques used and why)`],
    [`${id}-prompt`, `${name}, the Markdown prompt blueprint`],
    [`${id}-flowchart`, `${name}, the flowchart of the prompt's logic`],
    [`${id}-next-steps`, `${name}, suggested next steps (refinement, output application, integration)`],
  ];
}

export const BOOK_MAP: BookSection[] = [
  // ---------- Foreword and chapter 1 ----------
  ...group("craft-of-prompting", "foreword", [["dawn", "The Dawn of the Prompt Engineer"]]),
  ...group("craft-of-prompting", "ch1", [
    ["beyond-basic-questions", "Beyond Basic Questions: from casual user to deliberate designer"],
    ["iterative-heartbeat", "The Iterative Heartbeat: draft, test, analyze, refine"],
    ["goal-definition", "Goal Definition: the crucial first step"],
    ["paper-and-pencil", "The 'Paper and Pencil' Stage: planning your prompt"],
    ["thinking-like-engineer", "Thinking Like an Engineer: anticipating ambiguity and failure modes"],
    ["role-of-experimentation", "The Role of Experimentation: your personal workshop"],
    ["laying-groundwork", "Laying the Groundwork for Mastery"],
  ]),

  // ---------- Chapter 2: The Five Pillars ----------
  ...group("five-pillars", "ch2", [
    ["intro-anatomy", "Anatomy of an Effective Prompt: the five pillars"],
    ["context-setting-the-stage", "1. Context, Setting the Stage: how background turns noise into signal"],
    ["context-why-it-matters", "Why Context Matters for Language Systems"],
    ["context-types", "Types of Contextual Information"],
    ["context-setting-effectively", "Setting the Stage Effectively"],
    ["instructions-control-panel", "2. Instructions, The Control Panel: knobs and levers for precision"],
    ["instructions-characteristics", "Characteristics of Effective Instructions"],
    ["instructions-operating", "Operating the Control Panel"],
    ["examples-apprenticeship", "3. Examples, Apprenticeship by Demonstration: the guild system"],
    ["examples-why-works", "Why Demonstration Works So Well"],
    ["examples-using-effectively", "Using Examples Effectively"],
    ["examples-gold-star", "The Importance of Gold Star Selection"],
    ["constraints-guardrails", "4. Constraints, Guardrails and Speed Limits: keeping outputs on track"],
    ["constraints-why-necessary", "Why Boundaries Are Necessary"],
    ["constraints-types", "Types of Constraints"],
    ["constraints-implementing", "Implementing Guardrails, and finding the right balance"],
    ["delimiters-fences", "5. Delimiters, Semantic Fences: preventing conceptual cattle from straying"],
    ["delimiters-why-crucial", "Why Fencing is Crucial"],
    ["delimiters-building", "Building Clear Fences"],
    ["delimiters-common-choices", "Common Delimiter Choices"],
    ["delimiters-power", "The Power of Clear Fences"],
    ["synergy", "Bringing It All Together: the synergy of the pillars"],
    ["workshop-broken-prompt", "Workshop: the broken prompt and its diagnosis by pillar"],
    ["workshop-repair-steps", "Workshop: the repair process, steps 1 to 5"],
    ["workshop-why-it-works", "Why the Repaired Prompt Works"],
  ]),

  // ---------- Chapter 3: Foundational techniques ----------
  ...group("foundational-techniques", "ch3", [
    ["intro-two-modes", "Direct Instruction and Demonstration: the two foundational methods"],
    ["zero-shot-telegraph", "1. Zero-Shot Prompting, The Telegraph Method"],
    ["zero-shot-when-works", "When Does the Telegraph Method Work Best?"],
    ["zero-shot-why-works", "Why Does it Work? The power of learned patterns"],
    ["zero-shot-examples", "Markdown Examples of Zero-Shot Prompts (four)"],
    ["zero-shot-limitations", "Limitations of the Telegraph Method"],
    ["few-shot-recipe-card", "2. Few-Shot Learning, The Recipe Card Approach"],
    ["few-shot-why-show", "Why Show, Not Just Tell? The power of pattern matching"],
    ["few-shot-structure", "The Structure of a Recipe Card (Few-Shot Prompt)"],
    ["few-shot-examples", "Markdown Examples of Few-Shot Prompts (three)"],
    ["one-shot-vs-few-shot", "One-Shot vs. Few-Shot"],
    ["gold-star-quality-sampling", "3. Quality Sampling, Gold Star Selection"],
    ["gold-star-why", "Why Gold Star Examples Are Non-Negotiable"],
    ["gold-star-criteria", "Criteria for a Gold Star Example"],
    ["gold-star-finding", "Finding or Crafting Your Gold Star Examples"],
    ["practical-exercise", "Practical Exercise: from telegraph to recipe card (steps 1 to 5)"],
    ["why-few-shot-superior", "Why the Few-Shot Prompt is Superior"],
    ["choosing-tool", "Choosing Your Foundational Tool"],
  ]),

  // ---------- Appendix C: Markdown manual (beginner) ----------
  ...group("markdown-for-prompts", "appC", [
    ["intro", "Markdown Manual: formatting for clearer prompts"],
    ["headings", "1. Headings: organizing the blueprint"],
    ["emphasis", "2. Emphasis: highlighting critical instructions"],
    ["lists", "3. Lists: sequencing steps and presenting examples"],
    ["code-blocks", "4. Code Blocks"],
    ["inline-code", "5. Inline Code: highlighting specific terms or snippets"],
    ["blockquotes", "6. Blockquotes: offsetting quoted material"],
    ["horizontal-rules", "7. Horizontal Rules: simple visual separation"],
    ["tables", "8. Tables: requesting or demonstrating tabular data"],
    ["escaping", "9. Escaping Markdown Characters: referring to literals"],
    ["carpenter-tools", "The Carpenter's Marking Tools"],
  ]),

  // ---------- Chapter 4: Advanced techniques ----------
  ...group("reasoning-techniques", "ch4", [
    ["intro", "Advanced Techniques: guiding complex reasoning, the three techniques"],
    ["cot-clockwork", "1. Chain-of-Thought (CoT), The Clockwork Method"],
    ["cot-why-steps-help", "Why Does Detailing the Steps Help?"],
    ["cot-zero-shot", "Engaging the Clockwork 1: instruction-based (zero-shot CoT), with two Markdown examples"],
    ["cot-few-shot", "Engaging the Clockwork 2: few-shot CoT, the refund reasoning example"],
    ["cot-value-exposing", "The Value of Exposing the Mechanism"],
    ["cot-limitations", "Limitations of CoT"],
    ["tot-forking-paths", "2. Tree of Thoughts (ToT), The Forking Paths Technique, and its four moves"],
    ["tot-alternatives-evaluation", "Simulating Forking Paths 1: generating alternatives with explicit evaluation (library example)"],
    ["tot-self-correction", "Simulating Forking Paths 2: simulated self-correction and refinement loop (City Hall example)"],
    ["tot-few-shot-exploration", "Simulating Forking Paths 3: few-shot examples of exploration"],
    ["tot-advantages", "Advantages of Exploring the Branches"],
    ["tot-challenges", "Challenges of Managing the Exploration"],
    ["distill-essence", "3. Knowledge Distillation (Prompting), The Essence Extractor"],
    ["distill-why-simplify", "Why Simplify a Working Prompt?"],
    ["distill-process", "The Distillation Process: finding the essence"],
    ["distill-conceptual-example", "Conceptual Example: distilling a style prompt"],
    ["distill-mindset", "The Essence Extractor Mindset"],
    ["case-study-anya-challenge-prompt", "Case Study: Mapping the Maze, the challenge and Anya's prompt structure"],
    ["case-study-how-simulated", "How it Simulated Forking Paths"],
    ["case-study-outcome", "Outcome"],
    ["expanding-repertoire", "Expanding Your Prompting Repertoire"],
  ]),

  // ---------- Chapter 5: Structuring interaction ----------
  ...group("structure-and-protection", "ch5", [
    ["intro", "Structuring Interaction: clarity, control and security, the two facets"],
    ["tags-dewey", "1. Structuring Output with Tags, The Dewey Decimal System for Machines"],
    ["tagging-concept", "The Concept of Tagging Data (with the note on JSON)"],
    ["prompting-tagged-output", "Prompting for Tagged Output: demonstrating the Dewey system, three steps"],
    ["tagged-examples", "Markdown Examples of Prompts Requesting Tagged Output (contact information, argument summary)"],
    ["benefits-structure", "Benefits of Imposing Structure"],
    ["considerations", "Considerations"],
    ["delims-defensive", "2. Delimiters as Defensive Boundaries, Semantic Fences Revisited"],
    ["threat", "The Threat: Prompt Injection, the Trojan Horse Inside the Gates"],
    ["why-injection-works", "Why Does Injection Work? Blurring authority"],
    ["building-defenses", "Building the Defenses: strong fences and explicit guard orders"],
    ["secured-prompt-structure", "Putting It Together: a secured prompt structure"],
    ["why-more-secure", "Why This Approach Increases Security"],
    ["adversarial-stress-test", "3. Understanding Adversarial Inputs, Stress-Testing the Vault"],
    ["adversarial-strategies", "Common Adversarial Input Strategies (to test against)"],
    ["purpose-stress-testing", "The Purpose of Stress-Testing"],
    ["how-to-stress-test", "How to Stress-Test (Simulated)"],
    ["workshop-scenario", "Workshop: Hardening the Gates, the scenario, the vulnerable prompt V1 and its weakness analysis"],
    ["workshop-your-task", "Workshop: your task and the attack to keep in mind"],
    ["workshop-solution-v2", "Workshop: the protected prompt V2, its explanation and the workshop conclusion"],
    ["conclusion", "Structure for Clarity, Robustness, and Security"],
  ]),

  // ---------- Chapter 6: Domain-specific prompting ----------
  ...group("code-and-research", "ch6", [
    ["intro", "Domain-Specific Prompting: tailoring the craft (the woodworker and the violin), the two domains"],
    ["coding-forge", "1. Coding Assistance, The Blacksmith's Forge: hammering out code snippets"],
    ["why-prompt-for-code", "Why Prompt for Code? Leveraging trained patterns"],
    ["technique-context", "Essential Techniques 1: context is non-negotiable (setting the heat)"],
    ["technique-instructions", "Essential Techniques 2: precision in instructions (the hammer blows)"],
    ["technique-few-shot", "Essential Techniques 3: few-shot examples, the shaping forms for code"],
    ["technique-structured-explanations", "Essential Techniques 4: structured explanations, the Dewey Decimal System"],
    ["task-code-generation", "Common Task: code generation (forging new tools), the BMI example"],
    ["task-code-explanation", "Common Task: code explanation (understanding the craftsmanship), the JavaScript example"],
    ["task-debugging", "Common Task: debugging (finding flaws in the metal), the get_evens example"],
    ["task-translation", "Common Task: code translation (recasting the metal), the Java to Python example"],
    ["task-documentation", "Common Task: documentation and commenting (polishing the work), the docstring example"],
    ["forge-considerations", "Important Considerations When Working the Forge, and the closing on responsibility"],
    ["research-archivist", "2. Research and Analysis, The Archivist's Lens: retrieve, then analyze, and the three limits RAG addresses"],
    ["rag-workflow", "The RAG Workflow (Conceptual): retrieval, augmentation, generation"],
    ["simulating-rag", "Simulating RAG Principles via Prompting (the non-coder's approach), three steps"],
    ["example-policy", "Markdown Example 1: answering a question based on a specific policy document"],
    ["example-abstracts", "Markdown Example 2: summarizing findings from multiple research abstracts"],
    ["example-climate", "Markdown Example 3: extracting climate trends from abstracts (workflow and prompt)"],
    ["large-documents", "Handling Large Documents: strategies for extensive context"],
    ["power-of-lens", "The Power of the Archivist's Lens"],
    ["key-considerations", "Key Considerations, and the closing on the cornerstone technique"],
    ["adapting-craft", "Adapting the Craft to the Material, and the contrast of the two domains"],
  ]),

  // ---------- Chapter 7: Optimization and debugging ----------
  ...group("optimize-and-debug", "ch7", [
    ["intro", "Optimization and Debugging: refining for reliability, the three methods"],
    ["iterative-refinement", "1. Iterative Refinement, The Watchmaker's Patience: adjusting tiny gears, the loop"],
    ["stage-1-draft", "Stage 1: Draft (the initial assembly, V0)"],
    ["stage-2-test", "Stage 2: Test (observe the mechanism in action)"],
    ["stage-3-analyze", "Stage 3: Analyze (diagnose the flaws), including connecting flaws to pillars"],
    ["stage-4-refine", "Stage 4: Refine (make targeted adjustments)"],
    ["stage-5-repeat", "Stage 5: Repeat the Cycle"],
    ["essence-of-iteration", "The Essence of Iteration"],
    ["ab-testing", "2. A/B Testing, The Double-Blind Taste Test: the coffee analogy"],
    ["ab-steps", "The seven steps of an A/B test, including the success metrics"],
    ["ab-example", "A/B Testing Example: optimizing an instruction for tone"],
    ["controlled-comparison", "The Value of Controlled Comparison"],
    ["troubleshooting", "3. Troubleshooting Common Failures, Tracing Faulty Wiring"],
    ["problem-1", "Problem 1: Irrelevant or Off-Topic Output"],
    ["problem-2", "Problem 2: Incorrect Formatting"],
    ["problem-3", "Problem 3: Factual Errors / Hallucinations"],
    ["problem-4", "Problem 4: Undesired Tone or Style"],
    ["problem-5", "Problem 5: Inconsistent Output Quality"],
    ["problem-6", "Problem 6: Bias or Unfairness in Output"],
    ["problem-7", "Problem 7: Prompt Injection Success"],
    ["debugging-mindset", "The Debugging Mindset"],
    ["workshop-v0-v1", "Workshop: From Draft to Dependable, V0 and refinement cycle 1 (V0 to V1)"],
    ["workshop-v2", "Workshop: refinement cycle 2 (V1 to V2)"],
    ["workshop-v3", "Workshop: refinement cycle 3 (V2 to V3) and the workshop conclusion"],
    ["pursuit-of-perfection", "The Pursuit of Prompt Perfection"],
  ]),

  // ---------- Chapter 8: Ethics and responsibility ----------
  ...group("ethics-and-bias", "ch8", [
    ["intro", "Ethics and Responsibility: prompting with care, and the two facets of the chapter"],
    ["guiding-principles", "1. Guiding Principles (Constitutional AI concepts), The Hippocratic Oath for Systems: first, do no harm"],
    ["cai-conceptual", "How Does a Constitution Shape Behavior? (a conceptual view, three stages)"],
    ["why-matters", "Why This Matters to the Prompt Engineer (even if you do not write the constitution)"],
    ["prompting-in-alignment", "Prompting in Alignment (conceptual example) and the closing on trustworthy technology"],
    ["bias-lens-grinder", "2. Bias Detection and Mitigation, The Lens Grinder's Test: identifying and correcting distortions"],
    ["manifestations", "Manifestations of Bias: what distortions look like"],
    ["sources-of-distortion", "Sources of Distortion: where do flaws originate?"],
    ["test-kit", "The Lens Grinder's Test Kit: practical detection methods for non-coders"],
    ["mitigation", "Mitigation Through Prompting, and the closing on ongoing processes"],
    ["workshop-scenario", "Workshop: Ethical Audit, the scenario and the hiring prompt V1"],
    ["workshop-audit-steps", "Workshop: audit steps 1 to 5 (goal and stakes, subjectivity, input variation, biases, mitigation)"],
    ["workshop-v2", "Workshop: the revised prompt V2 and the workshop conclusion"],
    ["ethical-compass", "The Prompt Engineer's Ethical Compass"],
  ]),

  // ---------- Chapter 9: Cutting-edge methods ----------
  // The manuscript replaces the detailed text of sections 1 and 2 by an editorial placeholder; the approved text exists in
  // Prirucnik_Prompt_Engineering_B.docx and is what the lessons teach for those sections.
  ...group("tools-and-multimodal", "ch9", [
    ["intro", "Cutting-Edge Methods: expanding the interaction, the three areas"],
    ["tool-use-swiss-army", "1. Tool Use and Orchestration (MRKL concepts), The Swiss Army Knife Approach: the camping analogy and MRKL"],
    ["tool-why-needed", "Why the Need for Specialized Tools? (five limitations)"],
    ["tool-architecture", "The MRKL Architecture: controller, toolkit, integrator"],
    ["tool-interaction-flow", "Example Interaction Flow: the France population example"],
    ["tool-prompting", "Prompting in a World with Tool Use (four points and the travel example)"],
    ["tool-benefits-challenges", "Benefits and Challenges of the Swiss Army Knife Approach, and the closing on modular systems"],
    ["multimodal-theater", "2. Multimodal Prompting, The Theater Director's Craft: coordinating text, images and sound"],
    ["multimodal-how-understand", "How Do Systems Understand Multiple Modalities? (encoders, cross-modal training, fusion, generation)"],
    ["multimodal-examples", "The Theater Director's Prompt: five examples with multimodal inputs"],
    ["multimodal-power", "The Power of Orchestrating Modalities, Directorial Challenges and the closing"],
    ["museum-case-study", "Case Study: how a museum used multimodal prompts to generate exhibit descriptions"],
    ["collaborative-markdown", "3. Collaborative Markdown, A Hybrid Syntax for Human-AI Co-Creation: the idea, seven core ideas, cognitive and practical benefits"],
    ["cmd-implications", "Prompt Engineering Implications and Challenges of Collaborative Markdown"],
    ["note", "Note: Acknowledging the Pace of Change, principles versus implementations"],
    ["expanding-horizon", "Expanding the Prompt Engineer's Horizon"],
  ]),

  // ---------- Chapter 10: Real-world case studies ----------
  // The manuscript refers to "the previous response" for the review assistant V1, the methodology extractor and the stated
  // limitations finder; those templates exist in Prirucnik_Prompt_Engineering_B.docx and are what the lessons teach.
  ...group("case-studies", "ch10", [
    ["intro", "Real-World Case Studies: prompt engineering in action, the two case studies"],
    ["cs1-scenario", "Case Study 1: Customer Service Chatbots, The Switchboard Operator's Revival, the scenario revisited"],
    ["cs1-goal", "Case Study 1: the goal, building GadgetHelper for Global Gadgets Inc."],
    ["cs1-iter0", "Case Study 1, Iteration 0: the naive request (baseline failure)"],
    ["cs1-iter1", "Case Study 1, Iteration 1: grounding in facts (applying RAG principles)"],
    ["cs1-iter2", "Case Study 1, Iteration 2: injecting persona and empathy (context, instructions, few-shot examples)"],
    ["cs1-iter3", "Case Study 1, Iteration 3: enabling action with tools (MRKL principles)"],
    ["cs1-iter4", "Case Study 1, Iteration 4+: refining conversation, edge cases and consistency"],
    ["cs1-challenges", "Case Study 1: key challenges and learnings in building GadgetHelper"],
    ["cs1-conclusion", "Case Study 1: conclusion"],
    ["cs2-scenario", "Case Study 2: Scientific Research, The Lab Assistant Upgrade, the scenario revisited: augmenting expertise"],
    ["cs2-goal", "Case Study 2: the goal, an AI assistant for pre-review checks"],
    ["cs2-approach1", "Case Study 2, Approach 1: the comprehensive checklist prompt (techniques, prompt V1, challenges and refinements)"],
    ["cs2-approach2", "Case Study 2, Approach 2: focused, modular prompts (three example prompts, benefits and drawbacks)"],
    ["cs2-iterative-key", "Regardless of approach, iterative refinement is key"],
    ["cs2-ethics", "Ethical Considerations and Limitations: the lab assistant's boundaries"],
    ["cs2-conclusion", "Case Study 2: conclusion"],
    ["craft-in-context", "The Craft in Context"],
  ]),

  // ---------- Chapter 11: The future ----------
  ...group("the-future", "ch11", [
    ["intro", "The Future"],
    ["apprenticeship-loop", "1. How Systems Learn Preferences, The Apprenticeship Loop"],
    ["rlhf", "RLHF in Language Models"],
    ["why-it-matters", "Why This Matters for Your Prompting"],
    ["horizon", "2. Emerging Trends and Possibilities, The Horizon"],
    ["trend-autonomy", "Trend 1: increased autonomy and planning (agentic systems)"],
    ["trend-multimodality", "Trend 2: deeper multimodality"],
    ["trend-personalization", "Trend 3: enhanced personalization and memory"],
    ["trend-interaction", "Trend 4: more fluid interaction modalities"],
    ["trend-grounding", "Trend 5: improved grounding, factuality and uncertainty"],
    ["trend-safety", "Trend 6: co-evolution of capabilities and safety and ethics"],
    ["enduring-principles", "3. The Enduring Principles, Timeless Craft in a Changing World, and the closing"],
    ["appendices-intro", "Appendices: your reference toolkit and continuing guide (the six companion volumes)"],
  ]),

  // ---------- Appendix B: Template library (15 blueprints, three workshops of five) ----------
  // Every blueprint has the same four parts in the book: the scenario with its detailed explanation, the Markdown prompt
  // blueprint, the flowchart and the suggested next steps.
  ...group("blueprints-1", "appB", [
    ["intro", "Template Library: the workshop blueprints, starting with sound structures and how to use them"],
    ...blueprint(1, "Sales and Marketing Strategy Analysis (Perfume Launch)"),
    ...blueprint(2, "Warehouse Inventory and Dispatch Planning"),
    ...blueprint(3, "Production Material Flow Planning (Shift-Based)"),
    ...blueprint(4, "Banking Customer Analysis and Service Personalization"),
    ...blueprint(5, "Educational Lesson Plan Generation"),
  ]),
  ...group("blueprints-2", "appB", [
    ...blueprint(6, "Retail Inventory Replenishment and Shelf Allocation Strategy"),
    ...blueprint(7, "Pharmaceutical Market Analysis (Drug Registration and Potential)"),
    ...blueprint(8, "Call Center Interaction Analysis (Quality Assurance)"),
    ...blueprint(9, "Personalized Personal Finance Guidance (Authenticated User)"),
    ...blueprint(10, "Interactive To-Do List Management and Reporting"),
  ]),
  ...group("blueprints-3", "appB", [
    ...blueprint(11, "Language Learning Center Program and Student Management"),
    ...blueprint(12, "Laboratory Sample Analysis Tracking and Reporting"),
    ...blueprint(13, "Fitness Center Client Needs Assessment and Program Suggestion"),
    ...blueprint(14, "Investigative Journalism Assistance (Information Triage and Analysis)"),
    ...blueprint(15, "Scientific Research Paper Writing Assistance"),
    ["closing", "From Blueprints to Bespoke Tools: customization, contextualization, refinement and ethical scrutiny"],
  ]),

  // ---------- Appendix D: Techniques quick reference (48 techniques, one row of the book's table each) ----------
  ...group("techniques-reference", "appD", [
    ["intro", "Techniques Quick Reference: the expanded toolkit, how the table is laid out and why techniques are combined"],
    ["t-ab-testing", "A/B Testing (Double-Blind Taste Test)"],
    ["t-adversarial", "Adversarial Prompting (Stress-Testing)"],
    ["t-cai", "Constitutional AI (CAI) Principles"],
    ["t-ape", "Automatic Prompt Engineering (APE)"],
    ["t-bias-detection", "Bias Detection Prompts"],
    ["t-calibrated-self-eval", "Calibrated Self-Evaluation"],
    ["t-calibration", "Calibration Techniques (via Prompting)"],
    ["t-cot", "Chain-of-Thought (Clockwork Method)"],
    ["t-constitutional", "Constitutional Prompting"],
    ["t-constrained", "Constrained Generation (Guardrails)"],
    ["t-context-stuffing", "Context Stuffing (Grounding, RAG Principles)"],
    ["t-devils-advocate", "Devil's Advocate"],
    ["t-divide", "Divide and Conquer"],
    ["t-ensemble", "Ensemble Methods (Conceptual via Prompt)"],
    ["t-expert-persona", "Expert Persona Prompting"],
    ["t-explainability", "Explainability Prompts"],
    ["t-factuality", "Factuality Verification Prompts"],
    ["t-few-shot-cot", "Few-shot CoT"],
    ["t-few-shot", "Few-Shot Learning (Recipe Card Approach)"],
    ["t-hierarchical", "Hierarchical Prompting (Conceptual)"],
    ["t-hypothetical-doc", "Hypothetical Document Simulation"],
    ["t-in-context", "In-Context Learning (Equivalent to Few-Shot)"],
    ["t-iterative", "Iterative Refinement (Watchmaker's Patience)"],
    ["t-distillation", "Knowledge Distillation (Essence Extractor)"],
    ["t-maieutic", "Maieutic Prompting (Socratic Method)"],
    ["t-markdown", "Markdown Formatting"],
    ["t-metacognitive", "Metacognitive Prompting"],
    ["t-mrkl", "MRKL Systems (Swiss Army Knife Approach)"],
    ["t-multimodal", "Multimodal Prompting (Theater Director)"],
    ["t-multi-persona", "Multi-persona Dialogue"],
    ["t-prompt-tuning", "Prompt Tuning (Technical)"],
    ["t-quality-sampling", "Quality Sampling (Output Selection)"],
    ["t-react", "ReAct (Reason + Act)"],
    ["t-red-teaming", "Red Teaming"],
    ["t-reflexion", "Reflexion"],
    ["t-rlhf", "Reinforcement Learning from Human Feedback (Apprenticeship Loop)"],
    ["t-rag", "Retrieval-Augmented Generation (Archivist's Lens)"],
    ["t-schema", "Schema-Based Prompting"],
    ["t-self-consistency", "Self-Consistency"],
    ["t-self-critique", "Self-Critique"],
    ["t-chaining", "Sequential Task Processing (Chaining)"],
    ["t-simulated-user", "Simulated User Testing"],
    ["t-socratic", "Socratic Method"],
    ["t-template", "Template Prompting (Blueprints)"],
    ["t-tot", "Tree of Thoughts (Forking Paths)"],
    ["t-xml-json", "XML/JSON Tagging (Dewey Decimal System)"],
    ["t-zero-shot-cot", "Zero-shot CoT"],
    ["t-zero-shot", "Zero-Shot Learning (Telegraph Method)"],
    ["closing", "The closing note on the table: combine methods, experiment, test rigorously and refine"],
  ]),

  // ---------- Appendix A: Glossary (91 terms, one section each, taught in alphabetical groups) ----------
  ...group("glossary", "appA", [
    ["intro", "Glossary: the Prompt Engineer's Lexicon, from Alignment to Zero-Shot, and how to use it"],
    ["ab-testing", "A/B Testing (the Double-Blind Taste Test)"],
    ["accuracy", "Accuracy"],
    ["action-verbs", "Action-Oriented Verbs"],
    ["adversarial", "Adversarial Prompting (Stress-Testing)"],
    ["agent", "Agent (Agentic System)"],
    ["alignment", "Alignment"],
    ["analogy", "Analogy (Metaphor)"],
    ["anthropic", "Anthropic"],
    ["api", "API (Application Programming Interface)"],
    ["archivists-lens", "Archivist's Lens (the metaphor for RAG)"],
    ["bias", "Bias (in AI outputs)"],
    ["blacksmiths-forge", "Blacksmith's Forge (the metaphor for coding assistance)"],
    ["blueprint", "Blueprint (Prompt Template)"],
    ["cot", "Chain-of-Thought (CoT) Prompting (the Clockwork Method)"],
    ["chatbot", "Chatbot (Conversational Agent)"],
    ["clockwork", "Clockwork Method (the metaphor for Chain-of-Thought)"],
    ["code-generation", "Code Generation"],
    ["code-interpreter", "Code Interpreter Tool"],
    ["constraint", "Constraint (Guardrails and Speed Limits)"],
    ["context", "Context (Setting the Stage)"],
    ["context-window", "Context Window"],
    ["controller", "Controller/Router (in MRKL systems)"],
    ["debugging", "Debugging (Prompt Debugging)"],
    ["delimiter", "Delimiter (Semantic Fences)"],
    ["dewey", "Dewey Decimal System for Machines (the metaphor for tagged output)"],
    ["double-blind", "Double-Blind Taste Test (the metaphor for A/B testing)"],
    ["essence-extractor", "Essence Extractor (the metaphor for prompt distillation)"],
    ["ethics", "Ethics (in prompt engineering)"],
    ["example", "Example (Apprenticeship by Demonstration, the Recipe Card)"],
    ["fairness", "Fairness"],
    ["few-shot", "Few-Shot Learning (the Recipe Card Approach)"],
    ["five-pillars", "Five Pillars (of an effective prompt)"],
    ["forking-paths", "Forking Paths Technique (the metaphor for Tree of Thoughts)"],
    ["format", "Format"],
    ["gold-star", "Gold Star Selection (Quality Sampling)"],
    ["grounding", "Grounding"],
    ["guardrails", "Guardrails and Speed Limits (the metaphor for constraints)"],
    ["hallucination", "Hallucination"],
    ["hippocratic", "Hippocratic Oath for Prompts (the metaphor for Constitutional AI)"],
    ["instruction", "Instruction (the Control Panel)"],
    ["interpretability", "Interpretability (Explainability)"],
    ["iterative-refinement", "Iterative Refinement (the Watchmaker's Patience)"],
    ["json", "JSON (JavaScript Object Notation)"],
    ["knowledge-base", "Knowledge Base"],
    ["knowledge-distillation", "Knowledge Distillation (prompting context: the Essence Extractor)"],
    ["llm", "Large Language Model (LLM)"],
    ["lens-grinder", "Lens Grinder's Test (the metaphor for bias detection)"],
    ["markdown", "Markdown"],
    ["mitigation", "Mitigation (of bias or harm)"],
    ["mrkl", "MRKL (Modular Reasoning, Knowledge, and Language) Systems (the Swiss Army Knife Approach)"],
    ["multimodal", "Multimodal Prompting (the Theater Director's Craft)"],
    ["negative-constraint", "Negative Constraint"],
    ["objective-subjective", "Objective vs. Subjective"],
    ["one-shot", "One-Shot Learning"],
    ["optimization", "Optimization (Prompt Optimization)"],
    ["persona", "Persona (Role-Playing)"],
    ["placeholder", "Placeholder"],
    ["prompt", "Prompt"],
    ["prompt-engineering", "Prompt Engineering"],
    ["prompt-injection", "Prompt Injection (Hijacking)"],
    ["recipe-card", "Recipe Card Approach (the metaphor for few-shot learning)"],
    ["rl", "Reinforcement Learning (RL)"],
    ["rlhf", "Reinforcement Learning from Human Feedback, RLHF (the Apprenticeship Loop)"],
    ["rag", "Retrieval-Augmented Generation, RAG (the Archivist's Lens)"],
    ["reward-model", "Reward Model (RM)"],
    ["robustness", "Robustness"],
    ["role", "Role (Persona)"],
    ["safety", "Safety (AI Safety)"],
    ["schema", "Schema"],
    ["semantic-fences", "Semantic Fences (the metaphor for delimiters)"],
    ["shot", "Shot (in few-shot learning)"],
    ["specificity", "Specificity"],
    ["stereotype", "Stereotype"],
    ["structured-output", "Structured Output"],
    ["style", "Style"],
    ["summarization", "Summarization"],
    ["swiss-army", "Swiss Army Knife Approach (the metaphor for MRKL systems)"],
    ["system-prompt", "System Prompt (Meta Prompt)"],
    ["tag", "Tag (XML Tag)"],
    ["telegraph", "Telegraph Method (the metaphor for zero-shot prompting)"],
    ["temperature", "Temperature"],
    ["template", "Template (Prompt Template, Blueprint)"],
    ["theater-director", "Theater Director's Craft (the metaphor for multimodal prompting)"],
    ["token", "Token"],
    ["tone", "Tone"],
    ["tool", "Tool (in MRKL systems)"],
    ["training-data", "Training Data"],
    ["tot", "Tree of Thoughts, ToT (the Forking Paths Technique)"],
    ["watchmaker", "Watchmaker's Patience (the metaphor for iterative refinement)"],
    ["xml", "XML (Extensible Markup Language)"],
    ["zero-shot", "Zero-Shot Prompting (the Telegraph Method)"],
  ]),

  // ---------- Appendices E and F ----------
  ...group("resources-and-platforms", "appE", [
    ["intro", "Further Reading and Resources, Beyond the Workshop: continuing the journey"],
    ["foundational", "1. Foundational Concepts: strengthening the bedrock (computation and information, linguistics, logic and critical thinking)"],
    ["practical", "2. Practical Prompting Techniques: communities and craftsmanship (AI lab blogs, curated communities, experimentation platforms)"],
    ["staying-current", "3. Staying Current: navigating the information flow (newsletters, conference overviews, arXiv)"],
    ["ethics", "4. Ethics, Safety, and Responsibility: the essential compass (ethics resources, studies on bias, discussions on alignment)"],
    ["enduring-craft", "The Enduring Craft"],
  ]),
  ...group("resources-and-platforms", "appF", [
    ["intro", "Prompting Platforms and Tools, Where the Craft Happens: choosing your workbench"],
    ["cat-web", "1a. Simple Web Interfaces and Chatbots (the Ready-Made Hand Tool)"],
    ["cat-playground", "1b. Developer Playgrounds and Studios (the Well-Equipped Workbench)"],
    ["cat-api", "1c. APIs (the Raw Components and Wiring), including low-code tools"],
    ["cat-integrated", "1d. Integrated Tools and Applications (the Specialized Power Tool)"],
    ["choosing", "2. Choosing Your Workbench: key factors to consider"],
    ["free-vs-paid", "3. A Note on Free vs. Paid Tools"],
    ["privacy", "4. Data Privacy and Security: a non-negotiable consideration"],
    ["right-tool", "The Right Tool for the Task"],
  ]),
];

export function sectionsOfChapter(chapterSlug: string): BookSection[] {
  return BOOK_MAP.filter((s) => s.chapter === chapterSlug);
}
